[package]
name = "deview"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
config = "0.14.0"
dioxus = { version = "0.5", features = ["fullstack", "router"] }
dioxus-logger = "0.5"
review-database = { git = "https://github.com/petabi/review-database.git", tag = "0.30.0"}
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }

[features]
default = []
server = ["dioxus/axum"]
web = ["dioxus/web"]
