name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [server, web]
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - name: Check formatting
      run: cargo fmt -- --check --config group_imports=StdExternalCrate
    - name: Clippy
      run: >-
        cargo clippy --no-default-features --features="${{ matrix.features }}" --
        -D warnings -W clippy::pedantic
    - name: markdownlint
      uses: articulate/actions-markdownlint@v1

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Set PQ_LIB_DIR
      if: runner.os == 'macOS'
      run: echo "PQ_LIB_DIR=$(brew --prefix libpq)/lib" >> $GITHUB_ENV
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests
      run: cargo test --all-features --verbose
